# Generated by Django 3.1.4 on 2020-12-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stajaliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('geoSirina', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('geoDuzina', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.CharField(blank=True, max_length=500, null=True)),
                ('stajalista', models.ManyToManyField(to='autobuske_linije.Stajaliste')),
            ],
        ),
    ]
